data: 
    n_fft: 510 #默认510
    num_frames: 1024
    hop_length: 128
    spec_abs_exponent: 0.5
    spec_factor: 0.33
    window: 'sqrthann'
    
    normalize_audio: True
    spatial_channels: 1
    sample_rate: 16000
    max_audio_length: 128000